baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'My New Hugo Site'
theme: 'hugo-theme-stack'
paginate: 5

menu:
  main:
    - identifier: post
      name: Posting
      url: "post/"
      weight: 10
